export let data = [{
        url: 'https://www.warehousestationery.co.nz/on/demandware.static/-/Library-Sites-wsl-shared-library/default/dwcd375d89/Content/Category-Landing-Pages/technology/apple/fy21/s2455-iPhone-12mini-buy-now-988x494.jpg',
    },
    {
        url: 'https://creativepool.com/files/candidate/portfolio/full/930803.jpg',
    },
    {
        url: 'https://cdn.grabon.in/gograbon/images/web-images/uploads/1617801584557/apple-offers.jpg',
    },
    {
        url: 'https://ossaimaenterprise.com/wp-content/uploads/2020/10/headersml-desk-apple-watch-series-6-860x360-1.jpg',
    },
    {
        url: 'https://qmacstore.com/media/banner-macbook-air-chip-m1-qmac-store.png',
    },
];

export let products = [{
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
    {
        rating: 4,
        name: 'Yeezy Boost 350 V2 "Black Static" sneakers',
        oldPrice: '420 000 сум',
        newPrice: '300 000 сум',
        photoUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRWrYlGSZZLqQItVhGWlQuuo4OrhABkX69Qgf3WhhBhXFRGHwtYlVYZNCxZUjaNAca8SKc1p2PSaOEUgV_ZTpahi8vS2Q83givgTBog2rU&usqp=CAc',
    },
];