export enum Routes {
	WITHOUT_TABS = 'without-tabs',
	MY_PROFILE = 'my-profile',
	SETTINGS = 'settings',
	MY_ORDERS = 'my-orders',
	NEWS = 'news',
	ABOUT_US = 'about-us',
	LANGUAGE = 'language',
	ABOUT_APP = 'about-app',
	AUTHORIZATION = 'authorization',
	TABS = 'tabs',
	HOME_STACK = 'home-stack',
	HOME = 'home',
	PRODUCT_DETAILS = 'product-details',
	CATEGORIES_STACK = 'categories-stack',
	CATEGORIES = 'categories',
	PRODUCTS = 'products',
	FILTER = 'filter',
	FAVORITES = 'favorites',
	CART_STACK = 'cart-stack',
	CART = 'cart',
	PRE_CHECKOUT = 'pre-checkout',
	CHECKOUT = 'checkout',
	PROFILE_STACK = 'profile-stack',
	PROFILE = 'profile',
}
