export enum Routes {
	HOME = 'home',
	PRODUCT_DETAILS = 'product-details',
	CATEGORIES = 'categories',
	FAVORITES = 'favorites',
	CART = 'cart',
	PRE_CHECKOUT = 'pre-checkout',
	CHECKOUT = 'checkout',
	TMP_SCREEN = 'tmp-screen',
	PROFILE = 'profile',
	AUTHORIZATION = 'authorization',
	ABOUT_US = 'about-us',
	LANGUAGE = 'language',
	MY_PROFILE = 'my-profile',
	MY_ORDERS = 'my-orders',
	CATEGORY_PRODUCTS = 'category-products',
	FILTER = 'filter',
}
